# Generated by Django 3.1.5 on 2021-04-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='', upload_to='product_image/')),
            ],
        ),
    ]
