# Generated by Django 3.1.5 on 2021-05-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210511_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_price', models.IntegerField()),
                ('prod_qty', models.IntegerField()),
            ],
        ),
    ]
